from fpdf import FPDF
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "AI Audit Report – DorjeX", 0, 1, "C")
        self.ln(10)

    def add_section(self, title, content):
        self.set_font("Arial", "B", 12)
        self.cell(0, 10, title, 0, 1)
        self.set_font("Arial", "", 10)
        for line in content.split("\n"):
            self.multi_cell(0, 7, line)
        self.ln(5)

def generate_pdf_report(username, audit_df, kpi_result, ethics_result, filename="audit_report.pdf"):
    pdf = PDFReport()
    pdf.add_page()

    today = datetime.now().strftime("%Y-%m-%d %H:%M")
    pdf.set_font("Arial", "I", 9)
    pdf.cell(0, 10, f"Generated by {username} on {today}", 0, 1, "R")
    pdf.ln(5)

    summary = audit_df["Audit Result"].value_counts().to_string()
    pdf.add_section("1. Audit Summary", summary)

    kpi_text = "\n".join([f"- {k}" for k in kpi_result])
    pdf.add_section("2. KPI Assessment", kpi_text)

    eia_text = f"EIA Result: {ethics_result['eia_assessment']}\nSimilarity Score: {ethics_result['similarity_score']:.2f}"
    pdf.add_section("3. Ethical Reflex", eia_text)

    pdf.output(filename)
    return filename
